### ISSUE TITLE
Retirement State/Region input not working

### ISSUE THREAD

**Issue by mhagel** [regen-network/regen-web#1116]
**Describe the bug**

In `v4` branch

can’t input a State/Region in the Retire or Take or Send popups

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by victordelval** [comment]
@mhagel It seems that this API service from https://geodata.solutions/ is no longer available, what do you think?

```
curl https://geodata.solutions/api/api.php?type=getStates&countryId=US
```

**Comment by mhagel** [comment]
This looks promising https://www.npmjs.com/package/country-state-city

**Comment by victordelval** [comment]
yes, it looks good, thanks! I'm going to try it..

**Comment by victordelval** [comment]
@mhagel I've been doing some research and doing some tests.

I think a good option would be the library: `iso-3166-2`

* https://www.npmjs.com/package/iso-3166-2
* https://github.com/olahol/iso-3166-2.js

It also has an implementation of the types in the DefinitelyTyped repo:

* https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/iso-3166-2

Although it is a library that has not been updated for a long time, it offers good results for ISO 3166-2 codes (official subdivisions within a country).

Another advantage is that it is lighter since it does not offer other complementary data that is not necessary (currency, coordinates, etc.)

(*) Maybe a good idea in the future would be to fork the library and update the data.

Next, comparison of some differences with the `country-state-city` library and with the official ISO website ( https://www.iso.org/iso-3166-country-codes.html )

|  ISO Level 2  |  country-state-city  |  iso-3166-2  |  ISO website
|----------|:-------------:|:-------------:|------:|
| United States (US) |  66  |  57  |  [57](https://www.iso.org/obp/ui/#iso:code:3166:US) |
| US Minor Outlying Islands (UM) |  0  |  9  |  [9](https://www.iso.org/obp/ui/#iso:code:3166:UM)  |
| Spain (ES) |  28  |  69  |  [69](https://www.iso.org/obp/ui/#iso:code:3166:ES)  |
| France (FR) |  42  |  131  |  [124](https://www.iso.org/obp/ui/#iso:code:3166:FR)  |
| Kenya (KE) |  54  |  47  |  [47](https://www.iso.org/obp/ui/#iso:code:3166:KE)  |

(*) Search ISO website by country code:
* https://www.iso.org/obp/ui/#iso:code:3166:US

Also a good solution for the country list (3166-1):
* https://www.iso.org/obp/ui/#search (select "country codes")

|  ISO Level 1  |  file  |  country-state-city  |  iso-3166-2  |  ISO website
|----------|:-------------:|:-------------:|:-------------:|------:|
| countries |  221  |  250  |  249  |  [249](https://www.iso.org/obp/ui/#iso:code:3166:US) |

**Comment by victordelval** [comment]
I think that the jurisdiction field of the transactions that are based on these selectors (retirement, purchase and buy forms) should be set with such selectors based on `iso-3166-2` library, which give a good resolution of ISO-3166 codes, avoiding (at least for the moment) the check with the mapbox client via the `forwardGeocode` api which is done with the `getISOString` function

**Comment by victordelval** [comment]
@ryanchristo a question, or rather confirmation... 

To set the `jurisdiction` property (both in credits txs, etc. and in projects definition) the codes we use are those corresponding to the `ISO 3166` standard (official according to UN), right? 

being for the countries the codes `3166-1 alpha-2`, and when the subdivisions are fixed, the codes `3166-2` (which includes country + subdivision).

If this is so, maybe we should add a mention in the documentation corresponding to jurisdiction, for example here:
* https://buf.build/regen/regen-ledger/docs/main:regen.ecocredit.v1#regen.ecocredit.v1.MsgCreateProject
* https://buf.build/regen/regen-ledger/docs/main:regen.ecocredit.v1#regen.ecocredit.v1.MsgRetire

**Comment by mhagel** [comment]
>I think a good option would be the library: iso-3166-2

@victordelval This looks like a good solution.

**Comment by ryanchristo** [comment]
> To set the jurisdiction property (both in credits txs, etc. and in projects definition) the codes we use are those corresponding to the ISO 3166 standard (official according to UN), right?

This is partially correct. We don't want to be political at a protocol level so we don't require the country to be officially included in the ISO standard. We also can't make external queries in blockchain land otherwise we would introduce an opportunity for non-determinism (one node might query and get a successful response and another might query and get a failed response, producing two different versions of state). We would have to manage a list of accepted country codes and it would require an upgrade each time the list was updated and we would have to choose what countries are accepted or the list would be managed via governance and we could potentially have politically charged votes and opinions.

We use the same format but we are not strict about whether the codes are correct according to the ISO standard. We actually updated the documentation to no longer include a reference to ISO, which you can see here:

https://buf.build/regen/regen-ledger/docs/main:regen.ecocredit.v1alpha1#regen.ecocredit.v1alpha1.MsgCreateBatch

**Comment by victordelval** [comment]
hmm i understand..

@S4mmyb @mhagel @ryanchristo  we can take it for granted right now that in use cases (forms) where the `country` and `state/region` selectors are used (i.e. where we provide a fixed list of options to set the jurisdiction) the options that we show for the moment are those corresponding to iso-3166, right?

**Comment by victordelval** [comment]
Hi @erikalogie 

now in the state/region dropdown we are showing all the official subdivisions (iso-3166-2), in principle for all the countries, according to the UN / iso-3166

Some countries, like France, have more than 100 options, or even on rare occasions options with the same name, but different type of subdivision and therefore iso code...

Do you think that in the dropdown we show the code and type of subdivision in parentheses, accompanying the name of the region?

![state_region_selector_options.png](https://images.zenhubusercontent.com/61dc5360ba522a43271330c1/b61706cf-8f98-4f9d-ac12-08ecc3681e44)
