### ISSUE TITLE
Remove usage of "registry" naming in our repos and endpoints

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#1961]
This was discussed during the architecture call: https://www.notion.so/regennetwork/Engineering-Architecture-2023-07-06-c686348bcb2941ee8c0961a34589f3d2

Proposed renaming:
- `web-registry` package in `regen-web` repo to `web-marketplace`
- `registry-server` repo to `regen-server`
- api.registry.regen.network (and staging) to api.marketplace.regen.network or api.regen.network
- ~"Regen Registry" zenhub board to "Regen Engineering"~

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1961?planning-poker) with Zenhub @blushi @wgwz

**Comment by blushi** [comment]
@aaronc could you confirm the new names above are ok?

**Comment by wgwz** [comment]
Aaron suggested that we could do:

api.regen.network/marketplace/v1/

**Comment by blushi** [comment]
yeah I like api.regen.network/marketplace/v1/
although it would be nice to discuss further how we handle versioning in the future

**Comment by wgwz** [comment]
x-posting from a slack comment i made:
>just a thought regarding the name change task for the registry-server, and in particular the domain name change, perhaps we should socialize this a bit with partners like cambium and toucan. i.e. perhaps they’ve hardcoded/parametrized the current url in some scripts or something, where it would be nice to a heads up rather see something break or a change behavior (i.e. if we put a redirect in place)

**Comment by wgwz** [comment]
### Setting up the new domains

New domains as discussed so far:
- `api-staging.regen.network`
- `api.regen.network`

DNS info:
```
$ heroku domains --app regen-registry-server-staging
=== regen-registry-server-staging Heroku Domain

regen-registry-server-staging.herokuapp.com

=== regen-registry-server-staging Custom Domains

 Domain Name                        DNS Record Type DNS Target                                            SNI Endpoint    
 ────────────────────────────────── ─────────────── ───────────────────────────────────────────────────── ─────────────── 
 api-staging.registry.regen.network CNAME           quiet-mandarin-fydxnedq0gtkny95shmx9spq.herokudns.com maiasaura-61105 
 
$ heroku certs --app regen-registry-server-staging
Name             Common Name(s)                      Expires               Trusted  Type
───────────────  ──────────────────────────────────  ────────────────────  ───────  ────
maiasaura-61105  api-staging.registry.regen.network  2023-09-14 23:28 UTC  True     ACM
```
```
$ heroku domains --app regen-registry-server        
=== regen-registry-server Heroku Domain

regen-registry-server.herokuapp.com

=== regen-registry-server Custom Domains

 Domain Name                DNS Record Type DNS Target                                                   SNI Endpoint     
 ────────────────────────── ─────────────── ──────────────────────────────────────────────────────────── ──────────────── 
 api.registry.regen.network CNAME           corrugated-rhinoceros-3ra6hbuq26qgz7vn1mge857s.herokudns.com utahraptor-40813 
 
$ heroku certs --app regen-registry-server        
Name              Common Name(s)              Expires               Trusted  Type
────────────────  ──────────────────────────  ────────────────────  ───────  ────
utahraptor-40813  api.registry.regen.network  2023-09-14 23:18 UTC  True     ACM
```

When we set up the new domain, we will need to do the following:

1. add the new custom domains to the registry-server heroku apps using commands from this guide (https://devcenter.heroku.com/articles/custom-domains#add-a-custom-domain-with-a-subdomain)
2. add the required CNAME records to our DNS provider (also in the guide above)
3. if required, enable ACM for each of the heroku apps (https://devcenter.heroku.com/articles/automated-certificate-management)

### Preparing redirects in the server

We want these redirects in the server:
1. `api-staging.registry.regen.network/<path> => api-staging.regen.network/marketplace/v1/<path>`
2. `api.registry.regen.network/<path> => api.regen.network/marketplace/v1/<path>`

Where `<path>` is any of the the current endpoints that the registry-server currently has, here are the endpoints:
```                               
Proxy rewrite rule "^/ledger" ~> "/"
Proxy rewrite rule "^/ledger-rest" ~> "/"
delete '/files/:projectId/:key'
get '/'
get '/:url(*)'
get '/api-docs/swagger.json'
get '/csrfToken'
get '/iri-gen'
get '/metadata-graph/:iri'
get '/nonce'
post '/addresses'
post '/auth/login'
post '/auth/verification-email'
post '/buyers-info'
post '/contact'
post '/create-account-link'
post '/create-checkout-session'
post '/create-login-link'
post '/csrfToken'
post '/files'
post '/iri-gen'
post '/logout'
post '/mailerlite'
post '/recaptcha/v3/verify'
post '/recaptcha/verify'
post '/webhook'
```

### Things to consider

1. It doesn't make sense to include `get '/metadata-graph/:iri'`, `get '/iri-gen'` or `post '/iri-gen'` in the redirects. Otherwise we would have this:
    a. `api-staging.regen.network/marketplace/v1/metadata-graph/:iri`
    b. And this `metadata-graph` is not only a feature for the marketplace app AFAIU.
2. Similarly I think it doesn't make sense to include this in redirects `get '/api-docs/swagger.json'`

Suppose 1 and 2 above are correct, we'll have make the regen-web repo aware of that distinction. Because right now it's just using a single configuration value `VITE_API_URI`. I.e.
1. To logout a user the app would need to `POST api-staging.regen.network/marketplace/v1/logout`
2. But to get metadata for an iri would need `GET api-staging.regen.network/metadata/:iri`

While 2 above works, it's weird that 1 above has a version and 2 does not.
Of course, if we all agree, that whatever it's NBD, just put all these endpoints under `marketplace/v1` and call it a day, that would be simple.
But I suspect we probably can solve these problems in a better way by some more thinking about the names.

/cc @blushi @ryanchristo 

### Next steps for now

Building off your list @ryanchristo 

- [ ] rename the registry-server pipeline
- [ ] rename the registry-server [heroku apps](https://devcenter.heroku.com/articles/renaming-apps)
- [ ] set up and test the new domains (without url prefixes and in addition to the current domains)
- [ ] rename the registry-server github repo
- [ ] check [the heroku github integration](https://devcenter.heroku.com/articles/github-integration) and disconnect and reconnect to the new github repo, if needed
- [ ] set up the new url prefixes (BLOCKED - pending naming choices)
- [ ] set up the redirects in the server using HOST header (BLOCKED - pending naming choices)

**Comment by blushi** [comment]
what about adding a version to the /metadata endpoint too?

**Comment by blushi** [comment]
We should also rename the package web-registry to web-marketplace in the regen-web monorepo (see issue description) @wgwz

**Comment by ryanchristo** [comment]
@wgwz I reopened and moved back to in progress because I didn't see a pull request for updating `web-registry`. Looks like you moved it back to review, did I miss something?

**Comment by wgwz** [comment]
@ryanchristo sorry about that, i didn't do any of that intentionally. i do think it's worthwhile to create a separate task for that, i'll do that now and link it here so we can close this one.

**Comment by wgwz** [comment]
Closing this task, the last piece can be tracked separately in this ticket: https://github.com/regen-network/regen-web/issues/2009
