### ISSUE TITLE
Move buyers page to regen network website from app

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#2003]

**Comment by ryanchristo** [comment]
Pending confirmation with the core design team.

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2003?planning-poker) with Zenhub @flagrede @ryanchristo @wgwz

**Comment by flagrede** [comment]
I wonder if we should not split this task. Migrating all the sanity-based sections is fairly easy (90% of the page) but migrating the section for the featured projects (not sanity based) would require pulling a lot of code from registry.
If we migrate the sanity-based sections the task is like a 3/5 and if we want to migrate the featured projects it becomes more of an 8/13 task because we need to set up all the logic for ledger queries with regen-www and get all the code from hooks and react-query.
One other option to keep the section at a minimal cost would be to add it in sanity instead of fetching data from the ledger.

Thoughts @blushi @erikalogie @ryanchristo  ?

**Comment by ryanchristo** [comment]
As discussed on the architecture call:

- General agreement on getting the featured projects from Sanity instead of the ledger, from a technical standpoint
- We should also ask @Erika Logie how often we are expecting those featured projects to change

**Comment by erikalogie** [comment]
I think it is totally fine if they come from Sanity instead of the ledger. They likely will only change every 3-6 months.

**Comment by ryanchristo** [comment]
Marking this as blocked as discussions around where this page lives is still ongoing.
