### ISSUE TITLE
Error: cant create a project without a class ID

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2047]
**Describe the bug**

The initial metadata constructed on the `basic-info` page (following the `choose-credit-class` page when creating a new project) does not include the credit class ID (i.e. `regen:creditClassId`) and therefore it is not possible to create a project without the user knowing they need to manually add the credit class id to the metadata on the `metadata` page.

A user could also use a different credit class ID than they selected from the initial step in which case the credit class selected is not the credit class used when creating the project, i.e. the credit class is always determined by the metadata.

**To Reproduce**

1. Go to https://dev.app.regen.network/ecocredits/portfolio
2. Log in with account that is a credit class issuer
3. Go through the project creation flow without altering the metadata
4. Note project creation failed and see error in console:

**Expected behavior**

A user should not have to manually add `regen:creditClassId` with a valid credit class ID. The credit class ID used to create the project should be the ID of the credit class selected at the beginning of the project creation workflow.

**Screenshots**

![Screenshot from 2023-08-26 18-56-27](https://github.com/regen-network/regen-web/assets/12519942/2c822ace-1cea-40cd-a797-511558436d3f)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2047?planning-poker) with Zenhub @blushi @flagrede @ryanchristo @wgwz

**Comment by wgwz** [comment]
I'm having some trouble reproducing this issue reliably.
Some times I am able to create a project through the portfolio w/o any issue at all.
And it correctly has a `regen:creditClassId`.
And other times I am seeing the error.

It seems like if I refresh the basic-info page right after selecting the credit class, then it works.
But if I try to go straight through the process, then I encounter the reported error.
So it must be something related to caching of project metadata at that point (?)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWhWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c5015888c61071c3c08f2cead2c3a1a47b48ed7d/Screen%20Shot%202023-08-30%20at%208.16.01%20PM.jpg)

Screenshot above shows how immediately after selecting a credit class, the web browser thinks that the project's metadata is null.
However in the database, we can see that it's not the case by looking up the metadata for that project:
```
➜  ~ psql postgres://postgres:postgres@localhost:5432/regen_registry -c "COPY (select metadata from project where id = '51e4ca7a-4793-11ee-a649-c26700a3bae4') TO STDOUT" | jq "."     
{
  "@type": [
    "regen:C01-Project",
    "regen:Project-Page"
  ],
  "@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "qudt": "http://qudt.org/schema/qudt/",
    "unit": "http://qudt.org/vocab/unit/",
    "regen": "https://schema.regen.network#",
    "schema": "http://schema.org/",
    "geojson": "https://purl.org/geojson/vocab#",
    "qudt:unit": {
      "@type": "qudt:Unit"
    },
    "schema:url": {
      "@type": "schema:URL"
    },
    "schema:image": {
      "@type": "schema:URL"
    },
    "regen:videoURL": {
      "@type": "schema:URL"
    },
    "schema:location": {
      "@context": {
        "type": "@type",
        "@vocab": "https://purl.org/geojson/vocab#",
        "coordinates": {
          "@container": "@list"
        }
      }
    },
    "qudt:numericValue": {
      "@type": "xsd:double"
    },
    "regen:galleryPhotos": {
      "@container": "@list"
    }
  },
  "regen:creditClassId": "C01"
}
```

Then after completing the basic-info form we can see the data above being overwritten:
```
➜  ~ psql postgres://postgres:postgres@localhost:5432/regen_registry -c "COPY (select metadata from project where id = '51e4ca7a-4793-11ee-a649-c26700a3bae4') TO STDOUT" | jq "."
{
  "schema:name": "Foo",
  "regen:projectSize": {
    "qudt:unit": "unit:HA",
    "qudt:numericValue": "11"
  }
}
```

Because the browser thought the metadata was null, and we submit the basic info form, [we call this code](https://github1s.com/regen-network/regen-web/blob/HEAD/web-marketplace/src/hooks/projects/useProjectWithMetadata.ts#L151-L152), which has the affect of combining a null/undefined object and values that exist only within the basic form, that's why we see the overwrite happening.

So I think the solution is going to be to just clear the caching of the project right after the credit class is created.
Not 100% sure, but I think that should do the trick.

P.S. You can also see this working if you clear the cache using the react-query dev tools for the project by id query, right after selecting the credit class.
