### ISSUE TITLE
Add no credit class option when selecting credit class

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2160]
**Is your feature request related to a problem? Please describe.**

A user should have the option of creating a project without a credit class (i.e. an "open project" or "off-chain project").

**Describe the solution you'd like**

As a user, I should have the option of creating a project that is not associated with a credit class. When presented with a list of credit classes (or no credit classes), there should always be "without a credit class" option.

- https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=1195%3A46340&mode=design&t=WOSPNwEG4D2aiGOr-1

![image](https://github.com/regen-network/regen-web/assets/12519942/61970336-8a79-4b7f-8893-f959133d75f9)

**Describe alternatives you've considered (optional)**

NA

**Additional context (optional)**

TBD

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
@erikalogie was planning to make a few more tweaks to the design, so we should confirm with her before implementing.

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2160?planning-poker) with Zenhub @flagrede

**Comment by blushi** [comment]
@erikalogie please let us know once we have a final version for this

**Comment by erikalogie** [comment]
@blushi I think that the Figma that is linked is fine for this story. I'm hoping for feedback from @clevinson on this page (which can be a separate story): https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=1210%3A48545&mode=design&t=WOSPNwEG4D2aiGOr-1, but my instinct is to just leave it out because it feels more confusing than helpful to me. This Figma comp should also potentially be part of a separate story about turning a off chain project into an onchain project: https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=1295%3A81254&mode=design&t=WOSPNwEG4D2aiGOr-1.
